// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-vVapLIjU4Xs8Vl0gtP54yT1bKAFht5M',
    appId: '1:201906481378:web:cea61c242cca9f4c01d6bb',
    messagingSenderId: '201906481378',
    projectId: 'riverpod-app-d10b7',
    authDomain: 'riverpod-app-d10b7.firebaseapp.com',
    storageBucket: 'riverpod-app-d10b7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtCpX_xXqUckxU7NqMCq8Np2iGTx2pStQ',
    appId: '1:201906481378:android:43f7a6af0bf11bd101d6bb',
    messagingSenderId: '201906481378',
    projectId: 'riverpod-app-d10b7',
    storageBucket: 'riverpod-app-d10b7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJ7As56tCYtTyKL_SPXd0Od0r7v1O46Rw',
    appId: '1:201906481378:ios:8cf3e06eb5c393fb01d6bb',
    messagingSenderId: '201906481378',
    projectId: 'riverpod-app-d10b7',
    storageBucket: 'riverpod-app-d10b7.appspot.com',
    iosClientId: '201906481378-e2oulpamfa4hpe50evcf5bubm2ha5q4f.apps.googleusercontent.com',
    iosBundleId: 'com.example.hookTutorial',
  );
}
